# Generated by Django 3.2.18 on 2023-02-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'propietario',
                'verbose_name_plural': 'propietarios',
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_punto', models.CharField(max_length=100, verbose_name='Nombre')),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'punto',
                'verbose_name_plural': 'puntos',
                'ordering': ['nombre_punto'],
            },
        ),
        migrations.CreateModel(
            name='Subestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subestacion', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url_subestacion', models.URLField()),
                ('id_subestacion', models.IntegerField()),
                ('region', models.CharField(blank=True, choices=[('3', 'antofagasta'), ('11', 'araucania'), ('1', 'arica-parinacota'), ('4', 'atacama'), ('10', 'biobio'), ('5', 'coquimbo'), ('13', 'los-lagos'), ('12', 'los-rios'), ('9', 'maule'), ('7', 'metropolitana'), ('16', 'nuble'), ('8', 'ohiggins'), ('2', 'tarapaca'), ('6', 'valparaiso')], max_length=20, null=True, verbose_name='Region')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('id_punto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo_datos.punto')),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo_datos.propietario')),
            ],
            options={
                'verbose_name': 'subestacion',
                'verbose_name_plural': 'subestaciones',
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=100, verbose_name='Nombre')),
                ('largo', models.FloatField()),
                ('tension', models.CharField(blank=True, choices=[('44', '44KV'), ('66', '66KV'), ('110', '110KV'), ('154', '154KV'), ('220', '220KV'), ('345', '345KV'), ('500', '500KV')], max_length=20, null=True, verbose_name='Tension')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelo_datos.propietario')),
                ('puntos', models.ManyToManyField(related_name='get_lineas', to='modelo_datos.Punto')),
            ],
            options={
                'verbose_name': 'linea',
                'verbose_name_plural': 'lineas',
            },
        ),
    ]
