# Generated by Django 3.2.18 on 2023-02-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='puntos',
            field=models.ManyToManyField(related_name='get_linea', to='modelo_datos.Punto'),
        ),
        migrations.AlterField(
            model_name='subestacion',
            name='id_punto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_sub', to='modelo_datos.punto'),
        ),
    ]
